# Generated by Django 5.2.6 on 2025-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
    ]
